@ApiService_HostAddress = http://localhost:5515

GET {{ApiService_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ApiService_HostAddress}}/weatherforecast/01a0287d-723d-7c47-bfde-94b766fe2d13
Accept: application/json

###

POST {{ApiService_HostAddress}}/weatherforecast/
Content-Type: application/json
Accept: application/json

{
    "temperatureF": 46,
    "date": "2026-08-23",
    "temperatureC": 8
}